<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

?>

<div id="custom-component" data-bind="scope: 'custom-file'">
	<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
	{
		"#custom-component": {
			"Magento_Ui/js/core/app": {
				"components": {
					"custom-file": {
						"component": "Solveda_Cms/js/customViewModel",
						"template": "Solveda_Cms/custom-component-tpl"
					}
				}
			}
		}
	}
</script>