<div class="latest-products">
    <h2>Latest Products</h2>
    <div class="products-grid">
        <?php foreach ($block->getLatestProducts() as $product): ?>
            <div class="product-item" style="width: 200px; height: 300px;">
                <a href="<?php echo $block->escapeUrl($product->getProductUrl()); ?>">
                    <img src="<?php echo $block->escapeUrl($block->getImageUrl($product)); ?>" alt="<?php echo $block->escapeHtml($product->getName()); ?>" style="width: 150px; height: 200px" />
                </a>
                <div class="product-details">
                    <a class="product-name" href="<?php echo $block->escapeUrl($product->getProductUrl()); ?>">
                        <?php echo $block->escapeHtml($product->getName()); ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
