<?php
/**
* @var \Magento\Framework\View\Element\Template $block
*/
?>

<div class="lower-main-content">
    <div class="monthly-banner">
    <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/banners/monthlyWebBanner.webp') ?>" alt="monthly-banner">
    </div>

    <br><br>

    <div class="community-block">
        <div class=community-header>
        <h1>Be Part of Spencer's Community</h1>
        </div>
        <div class="community-container">
            <div class="row">
                <div style="width:23%; float:left; margin:1%;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/spencer-community/bestSeller.jpg') ?>" width="295px" height="185px" style="width:100%" alt="Best Deals"></a>
                </div>
                <div style="width:23%; float:left; margin:1%;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/spencer-community/coupon.jpg') ?>" width="295px" height="185px" style="width:100%" alt="Coupon"></a>
                </div>
                <div style="width:23%; float:left; margin:1%;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/spencer-community/brands.jpg') ?>" width="295px" height="185px" style="width:100%" alt="Top Brands"></a>
                </div>
                <div style="width:23%; float:left; margin:1%;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/spencer-community/deal.jpg') ?>" width="295px" height="185px" style="width:100%" alt="Deal"></a>
                </div>
            </div>
        </div>
    </div>

    <br><br>
    <br><br>

    <div class="bottom-block">
        <div class="row">
        <div style="width: 100%; float:left; background-color: #e5e5e5; height: auto;">
            <div style="width:23%; float:left; margin:1%">
                <div style="width:40%; float:left; padding-top:20%;">
                <span>Personal Care</span><br>
                </div>
                <div style="width:60%; float:left;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/main-bottom-images/block1_a.jpg') ?>" class="img-responsive" style="width:100%" alt="Personal Care">
                </div>
            </div>
            <div style="width:23%; float:left; margin:1%">
                <div style="width:40%; float:left; padding-top:20%;">
                <span>Home & Kitchen</span><br>
                </div>
                <div style="width:60%; float:left;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/main-bottom-images/homeKitchen_a.jpg') ?>" class="img-responsive" style="width:100%" alt="Home & Kitchen">
                </div>
            </div>
            <div style="width:23%; float:left; margin:1%">
                <div style="width:40%; float:left; padding-top:20%;">
                <span>Electronics & Electrical</span><br>
                </div>
                <div style="width:60%; float:left;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/main-bottom-images/ene_b.jpg') ?>" class="img-responsive" style="width:100%" alt="Electroics">
                </div>
            </div>
            <div style="width:23%; float:left; margin:1%">
                <div style="width:70%; float:left; padding-top:20%;">
                <span>Download App</span><br>
                </div>
                <div style="width:30%; float:left;">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('Solveda_Cms::images/main-bottom-images/app.jpg') ?>" class="img-responsive" style="width:90%" alt="App">
                </div>
            </div>
        </div>
        </div>
    </div>

    <br><br>
    <br><br>
</div>