<form id="price-calculator-form">
    <label for="quantity">Quantity:</label>
    <input type="text" id="quantity" data-bind="value: quantity, valueUpdate: 'afterkeydown'">

    <br>

    <label for="unit-price">Unit Price:</label>
    <input type="text" id="unit-price" data-bind="value: unitPrice, valueUpdate: 'afterkeydown'">

    <br>

    <label for="total">Total:</label>
    <span data-bind="text: total"></span>
</form>

<script type="text/x-magento-init">
{
    "#price-calculator-form": {
        "Magento_Ui/js/core/app": {
            "components": {
                "priceCalculatorForm": {
                    "component": "Solveda_Cms/js/price-calculator-form"
                }
            }
        }
    }
}
</script>
