<?php
if($block->getCategories()){
    $categoryCollection = $block->getCategories();
}
?>
<div class="main-upper-content">
    <div class="left-content" style="width:20%; float:left;">
        <div class="category-list">
            <?php foreach ($categoryCollection as $category): ?>
            <div class = "category-tree" data-category-id="<?= $category->getId() ?>">
            <img src="<?= $block->getCategoryImage($category); ?>" alt="cat-image">
            <div><?php echo $category->getName(); ?></div>
            </div>
            <?php endforeach; ?>
        </div>
        </div>
    </div>

    <div class="right-content" style="width:80%; float:right;">
        <div class="left-banner">
            <div class="website-banner" style="width:50%; float:left;">
            <img src="<?= $block->getUpperImage(); ?>" alt="Website Banner">
            </div>
        </div>
        <div class="right-banners" style="width:50%; float:left;">
            <div class="upper-banner">
            <img src="<?= /* @noEscape */ $block->getRightImage1(); ?>" alt="Right 1st Banner">
            </div>
            <div class="lower-banner">
            <img src="<?= /* @noEscape */ $block->getRightImage2(); ?>" alt="Right 1st Banner">
            </div>
        </div>
    </div>
</div>

<div id="childCategoriesContainer" class="child-categories-container" style="display:none">
    
</div>

<script>
    require(['jquery'], function($) {
    $(document).ready(function () {

        $('.category-list').on('click', '.category-tree', function () {
        var categoryId = $(this).data('category-id');
        
            $.ajax({
                url: '/home/index/loadsubcategories',
                type: 'POST',
                dataType: 'json',
                data: {category_id: categoryId},
                success: function (response) {
                if (response.success) {
                    var childCategories = response.categories;
                    console.log(childCategories);
                    
                    if (childCategories.length > 0) {
                        displayChildCategories(childCategories);
                    } else {
                        window.location.href = '/catalog/category/view/id/' + categoryId;
                    }
                } else {
                    console.error('Error: ' + response.error);
                }
            },
            error: function () {
                console.error('AJAX request failed');
            }
        });
    });

    function displayChildCategories(childCategories) {
        var container = $('#childCategoriesContainer');
        container.empty();

        var content = '<div class="child-categories">';
        childCategories.forEach(function (category) {
            content += '<div data-category-id="' + category.id + '">' + category.name + '</div>';
        });
        content += '</div>';

        container.append(content).toggle();

        container.on('click', '.child-categories div', function () {
            var childCategoryId = $(this).data('category-id');
            // Navigate to the child category page
            window.location.href = '/catalog/category/view/id/' + childCategoryId;
        });
    }

            
    });
});
</script>
