<?php
if($block->getCategories()){
    $categoryCollection = $block->getCategories();
}
?>
<div class="main-upper-content">
    <div class="left-content" style="width:20%; float:left;">
        <div class="category-list">
            <?php foreach ($categoryCollection as $category): ?>
            <div>
            <img src="<?= $block->getCategoryImage($category); ?>" alt="cat-image">
            <a href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?></a>
            </div>
            <?php endforeach; ?>
        </div>
        </div>
    </div>

    <div class="right-content" style="width:80%; float:right;">
        <div class="left-banner">
            <div class="website-banner" style="width:50%; float:left;">
            <img src="<?= $block->getUpperImage(); ?>" alt="Website Banner">
            </div>
        </div>
        <div class="right-banners" style="width:50%; float:left;">
            <div class="upper-banner">
            <img src="<?= /* @noEscape */ $block->getRightImage1(); ?>" alt="Right 1st Banner">
            </div>
            <div class="lower-banner">
            <img src="<?= /* @noEscape */ $block->getRightImage2(); ?>" alt="Right 1st Banner">
            </div>
        </div>
    </div>
</div>
