<button type="button" class="offer-list">
    Offer
</button>

<div id="offerlist" style="display: none; position: absolute; background-color: #fff; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); border: 1px solid #ccc; z-index: 1000;">
    <h2>Tracking Order</h2>
<div><a href="#">Shopping List</a></div>
<div><a href="">Offer</a></div>
</div>


<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.offer-list').click(function() {
                $('#offerlist').toggle();
            });
        });
    });
</script>