<div class="contact-info">
    <h3>Contact Us</h3>
    <p>
        <span class="email-icon">
        <i class="fa fa-envelope" style="font-size:36px"></i>
        </span>
        <span>Email:<a href="#">customercare@example.com</a></span></p>
    <p>
    <span class="phone-icon">
    <i class="fa fa-phone" style="font-size:36px"></i>
    </span>
    <span>Telephone: 12345678</span><br>
    <span>Location: 1233 , Canaught Palace, New Delhi<span>
    </p>
</div>
