<div class="contact-info">
    <h3>Contact Us</h3>
    <p>
        <span class="email-icon">
        <i class="fa fa-envelope" style="font-size:36px"></i>
        </span>
        <span>Email:<?php echo $block->getEmail();?></span></p>
    <p>
    <span class="phone-icon">
    <i class="fa fa-phone" style="font-size:36px"></i>
    </span>
    <span>Telephone: <?php echo $block->getPhone();?></span><br>
    <span>Location:<?php echo $block->getAddress();?><span>
    </p>
</div>
