<?php
/*
* @var \Magento\Framework\View\Element\Html\Link $block
*/
?>

<div class="info-div">
    <h3>Information</h3>
    <a href="<?=$block->getUrl('about-us')?>">About Us</a><br>
    <a href="<?=$block->getUrl('customer-service')?>">Customer Service</a><br>
    <a href="#">Locate Us</a><br>
    <a href="#">Heritage</a><br>
    <a href="#">Differentiators</a><br>
    <a href="#">Innovation</a><br>
    <a href="#">Awards</a><br>
    <a href="#">Milestone</a><br>
    <a href="#">Corporate Login</a><br>
    <a href="#">FAQs</a><br>
</div>