<div class="footer-summary">
    <div class="summary-1">
        <p><b>Convenience at its best:</b> With 57,000+ products in store, Spencer’s offers you the convenience of ordering online and getting all your products delivered right at your doorstep in a maximum of 3 hours. Get all your online grocery shopping done in a matter of minutes.</p>
    </div><br>
    <div class="summary-2">
        <p><b>You Name It, We Have It:</b> Spencer’s meets all your grocery and home-based needs across categories like Fruits & Vegetables, Groceries & Staples, Organic, Bakery & Eggs & Dairy, Coffee &Tea & Beverages, Packaged Food, Imported & Gourmet, Fish & Meat, Baby Care, Personal Care, Bathroom & Cleaning, Home & Dining,Apparel.</p>
    </div><br>
    <div class="summary-3">
        <p><b>Our Service Locations:</b> With a constantly growing network, Spencer’s is currently providing its service to the cities of Kolkata, Noida, Gurgaon, Delhi, Ghaziabad,Varanasi, Dehradun, Allahabad, Chennai, Hyderabad, Lucknow, Vizag.</p>
    </div><br>
    <div class="summary-4">
        <p><b>Payment Options:</b> There are a number of cashless payment options that are available to customers like Net Banking, PayTM, Card on Delivery that make it convenient for everyone to pay. Avail of great online grocery offers and discounts by ordering online and making your life easy and simple.</p>
    </div><br>
</div>